on:
  push:
    tags:
      - '*'

name: Release

jobs:
  build-ubuntu-x86_64:
    name: Ubuntu (x86_64)
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libgl-dev libglu1-mesa-dev libgtk-3-dev libjack-dev libmad0-dev libpulse-dev libudev-dev libxinerama-dev libx11-dev libxrandr-dev libxtst-dev nasm
      - name: Create full release
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off
      - name: Create package
        id: package
        run: cmake --build build --target package
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: StepMania-${{ github.ref_name }}-Ubuntu (x86_64)
          path: build/StepMania-*.tar.gz
          archive: false
      - uses: actions/attest@v6
        with:
          subject-name: StepMania-${{ github.ref_name }}-Ubuntu (x86_64)
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

  build-ubuntu-arm:
    name: Ubuntu (ARM)
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libgl-dev libglu1-mesa-dev libgtk-3-dev libjack-dev libmad0-dev libpulse-dev libudev-dev libxinerama-dev libx11-dev libxrandr-dev libxtst-dev libusb-1.0-0-dev libusb-dev nasm
      - name: Create full release
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off
      - name: Create package
        id: package
        run: cmake --build build --target package
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: StepMania-${{ github.ref_name }}-Ubuntu (ARM)
          path: build/StepMania-*.tar.gz
          archive: false
      - uses: actions/attest@v6
        with:
          subject-name: StepMania-${{ github.ref_name }}-Ubuntu (ARM)
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

  build-macos-arm:
    name: macOS (arm64)
    runs-on: macos-15
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        run: brew install nasm
      - name: Create full release
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off -DCMAKE_OSX_ARCHITECTURES=arm64
      - name: Create package
        id: package
        run: cmake --build build --target package
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: StepMania-${{ github.ref_name }}-macOS (arm64)
          path: build/StepMania-*.dmg
          archive: false
      - uses: actions/attest@v6
        with:
          subject-name: StepMania-${{ github.ref_name }}-macOS (arm64)
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

  build-macos-intel:
    name: macOS (x86_64)
    runs-on: macos-15-intel
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        run: brew install nasm
      - name: Create full release
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off -DCMAKE_OSX_ARCHITECTURES=x86_64
      - name: Create package
        id: package
        run: cmake --build build --target package
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: StepMania-${{ github.ref_name }}-macOS (Intel)
          path: build/StepMania-*-macOS-Intel-no-songs.dmg
          archive: false
      - uses: actions/attest@v6
        with:
          subject-name: StepMania-${{ github.ref_name }}-macOS (Intel)
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

  build-windows:
    name: Windows
    runs-on: windows-2022
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Create full release
        run: cmake -B build -DWITH_FFMPEG_JOBS="$env:NUMBER_OF_PROCESSORS" -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off
      - name: Create package
        id: package
        run: cmake --build build --config Release --target package
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: StepMania-${{ github.ref_name }}-Windows
          path: build/StepMania-*.exe
          archive: false
      - uses: actions/attest@v6
        with:
          subject-name: StepMania-${{ github.ref_name }}-Windows
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}